# Autoprefix your CSS for browser compatibility
BROWSERS:
  - "Chrome >= 35"
  - "Firefox >= 31"
  - "Edge >= 12"
  - "Explorer >= 9"
  - "iOS >= 8"
  - "Safari >= 8"
  - "Android 2.3"
  - "Android >= 4"
  - "Opera >= 12"

# The name of your .css and .js files
FILENAME: "app"

# Include temp/holder.min.js in the output directory for placeholder images
INCLUDE_HOLDER: true

# Your project's paths
PATHS:
  #Local web server root path, output from 'npm start', e.g. "_site"
  site: "dist" 
  #The build path, output from 'npm run build'
  build: "dist"
  #Javascript, optimize .js size by commenting out unused scripts
  js:
    #JQuery
    - "node_modules/jquery/dist/jquery.min.js"
    #Bootstrap
    - "node_modules/bootstrap/js/dist/util.js"
    - "node_modules/bootstrap/js/dist/alert.js"
    - "node_modules/bootstrap/js/dist/button.js"
    - "node_modules/bootstrap/js/dist/carousel.js"
    - "node_modules/bootstrap/js/dist/collapse.js"
    - "node_modules/bootstrap/js/dist/dropdown.js"
    - "node_modules/bootstrap/js/dist/modal.js"
    - "node_modules/bootstrap/js/dist/scrollspy.js"
    - "node_modules/bootstrap/js/dist/tab.js"
    - "node_modules/bootstrap/js/dist/tooltip.js"
    - "node_modules/bootstrap/js/dist/popover.js"

# The port your project's local web server will use, e.g. 8080
PORT: 8080

# Sass configurations, includePaths has "node_modules/" to find Bootstrap 
SASS_OPTIONS:
  errLogToConsole: true
  outputStyle: "expanded"
  includePaths: "node_modules/"
