# Autoprefix your CSS for browser compatibility
BROWSERS:
  - "Chrome >= 35"
  - "Firefox >= 31"
  - "Edge >= 12"
  - "Explorer >= 9"
  - "iOS >= 8"
  - "Safari >= 8"
  - "Android 2.3"
  - "Android >= 4"
  - "Opera >= 12"

# The name of your .css and .js files
FILENAME: "app"

# Include temp/holder.min.js in the output directory for placeholder images
INCLUDE_HOLDER: true

# Your project's paths
PATHS:
  #Local web server root path, output from 'npm start', e.g. "_site"
  site: "dist" 
  #The build path, output from 'npm run build'
  build: "dist"
  # Javascript, optimize .js size by commenting out unused scripts
  js:
    # JQuery
    - "node_modules/jquery/dist/jquery.min.js"
    # Bootstrap
    - "node_modules/bootstrap/js/dist/util.js"
    - "node_modules/bootstrap/js/dist/alert.js"
    - "node_modules/bootstrap/js/dist/button.js"
    - "node_modules/bootstrap/js/dist/carousel.js"
    - "node_modules/bootstrap/js/dist/collapse.js"
    - "node_modules/bootstrap/js/dist/dropdown.js"
    - "node_modules/bootstrap/js/dist/modal.js"
    - "node_modules/bootstrap/js/dist/scrollspy.js"
    - "node_modules/bootstrap/js/dist/tab.js"
    # Add tether.js to the project if you are including tooltip.js or popover.js
    - "node_modules/bootstrap/js/dist/tooltip.js"
    - "node_modules/bootstrap/js/dist/popover.js"

# The port your project's local web server will use, e.g. 8080
PORT: 8080

# Sass configurations, includePaths has "node_modules/" to find Bootstrap 
SASS_OPTIONS:
  errLogToConsole: true
  outputStyle: "expanded"
  includePaths: "node_modules/"

# Run UnCSS on production builds, experimental
UNCSS_ON: false

# Paths and ignores for UnCSS
# TODO These ignores have only been tested against Bootstrap 3. Update to Bootstrap 4.
UNCSS_OPTIONS:
  html:
    - "html/**/*.html"
  ignore:
    - ".bs.carousel"
    - ".slid.bs.carousel"
    - ".slide.bs.carousel"
    - ".fade"
    - ".fade.in"
    - ".collapse"
    - ".collapse.in"
    - ".collapsing"
    - ".alert-danger"
    - ".logged-in .navbar-default"
    - ".carousel-inner > .next"
    - ".carousel-inner > .prev"
    - ".carousel-inner > .next"
    - ".carousel-inner > .prev"
    - ".carousel-inner > .next.left"
    - ".carousel-inner > .prev.right"
    - ".carousel-inner > .active.left"
    - ".carousel-inner > .active.right"
    - "#float-toc"
    - "#float-toc a"
    - ".modal-content"
    - ".modal-header"
    - ".modal-body"
    - ".modal-dialog"
    - ".modal.fade.in"
    - ".modal-open"
    - /(#|\.)modal(\-[a-zA-Z]+)?/
    - ".navbar-toggle.open"
    - ".fade .modal-dialog"
    - ".navbar-collapse.in"
    - ".navbar-fixed-top"
    - ".logged-in .navbar-fixed-top"
    - ".navbar-collapse"
    - ".navbar-collapse.in"
    - ".navbar-inverse .innovations.navbar-toggle.open"
    - ".single-innovation .navbar-inverse .innovations.navbar-toggle.open"
    - "#innovations.collapse.in"
    - "ul.page-numbers li a.prev"
    - ".open"
    - ".open > .dropdown-menu"
    - ".open > a"
    - ".alert-danger"
    - ".visible-xs"
    - ".noscript-warning"
    - ".close"
    - ".alert-dismissible"
    - ".page.calendar .events .panel:hover .fa-angle-down.open"
    - ".fa-angle-down.open"
